fix Bignum no longer being visitable
test sadly does not fail without it, but tried this patch in classic and it solves the issue :(

```
TypeError: Cannot visit Bignum
    vendor/bundle/ruby/2.2.0/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:25:in `rescue in visit'
```